name: Deploy to SFTP

on:
  push:
    branches:
      - master

jobs:
  sftp-deploy:
    name: SFTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          source: "."
          target: "/mods"
